# Generated by Django 3.0.3 on 2020-03-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(help_text='字母简称', max_length=15, unique=True, verbose_name='idc字母简称')),
                ('name', models.CharField(help_text='idc名称', max_length=30, verbose_name='idc名称')),
                ('address', models.CharField(help_text='idc具体地址', max_length=255, null=True, verbose_name='idc具体地址')),
                ('tel', models.CharField(blank=True, help_text='负责人电话', max_length=15, null=True, verbose_name='负责人电话')),
                ('mail', models.EmailField(blank=True, help_text='负责人邮箱', max_length=255, null=True, verbose_name='负责人邮箱')),
                ('remark', models.CharField(blank=True, help_text='备注说明', max_length=255, null=True, verbose_name='备注说明')),
            ],
            options={
                'db_table': 'resources_idc',
                'ordering': ['id'],
            },
        ),
    ]
