# Generated by Django 3.0.3 on 2020-03-02 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='机柜名称', max_length=50, verbose_name='机柜名称')),
                ('idc', models.ForeignKey(help_text='所在机房', on_delete=django.db.models.deletion.CASCADE, to='idcs.Idcs', verbose_name='所在机房')),
            ],
            options={
                'db_table': 'resources_cabinet',
                'ordering': ['id'],
            },
        ),
    ]
