# Generated by Django 3.0.3 on 2020-03-02 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet', '0001_initial'),
        ('idcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(help_text='制造商', max_length=255, null=True, verbose_name='制造商')),
                ('os', models.CharField(default=None, help_text='操作系统', max_length=100, verbose_name='操作系统')),
                ('hostname', models.CharField(db_index=True, default=None, help_text='主机名', max_length=50, verbose_name='主机名')),
                ('ip', models.CharField(db_index=True, default=None, help_text='IP', max_length=32, verbose_name='IP')),
                ('cpu', models.CharField(default=None, help_text='CPU信息', max_length=250, verbose_name='CPU信息')),
                ('disk', models.CharField(help_text='硬盘信息', max_length=300, null=True, verbose_name='硬盘信息')),
                ('server_mem', models.CharField(default=None, help_text='内存信息', max_length=100, verbose_name='内存信息')),
                ('status', models.CharField(db_index=True, help_text='状态', max_length=32, null=True, verbose_name='状态')),
                ('uuid', models.CharField(db_index=True, help_text='UUID', max_length=100, null=True, unique=True, verbose_name='UUID')),
                ('sn', models.CharField(db_index=True, help_text='SN', max_length=40, null=True, verbose_name='SN')),
                ('model_name', models.CharField(default=None, help_text='型号', max_length=255, verbose_name='型号')),
                ('last_check', models.DateTimeField(auto_now=True, help_text='上次检测时间', verbose_name='上次检测时间')),
                ('use', models.CharField(default=None, help_text='用途', max_length=35, verbose_name='用途')),
                ('cabinet', models.ForeignKey(help_text='所在机柜', null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Cabinet', verbose_name='所在机柜')),
                ('idc', models.ForeignKey(help_text='所在机房', null=True, on_delete=django.db.models.deletion.CASCADE, to='idcs.Idcs', verbose_name='所在机房')),
            ],
            options={
                'db_table': 'resources_server',
            },
        ),
    ]
