# Generated by Django 3.0.3 on 2020-03-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='server_mem',
        ),
        migrations.AddField(
            model_name='server',
            name='mem',
            field=models.CharField(blank=True, default=None, help_text='内存信息', max_length=100, verbose_name='内存信息'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu',
            field=models.CharField(blank=True, default=None, help_text='CPU信息', max_length=250, verbose_name='CPU信息'),
        ),
        migrations.AlterField(
            model_name='server',
            name='disk',
            field=models.CharField(blank=True, help_text='硬盘信息', max_length=300, null=True, verbose_name='硬盘信息'),
        ),
        migrations.AlterField(
            model_name='server',
            name='model_name',
            field=models.CharField(blank=True, default=None, help_text='型号', max_length=255, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.CharField(blank=True, default=None, help_text='操作系统', max_length=100, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(blank=True, db_index=True, help_text='SN', max_length=40, null=True, verbose_name='SN'),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, help_text='UUID', max_length=100, null=True, unique=True, verbose_name='UUID'),
        ),
    ]
