# Generated by Django 3.0.3 on 2020-03-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20200302_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(default=None, help_text='主机密码', max_length=32, verbose_name='主机密码'),
        ),
        migrations.AddField(
            model_name='server',
            name='username',
            field=models.CharField(default=None, help_text='主机用户名', max_length=32, verbose_name='主机用户名'),
        ),
    ]
