# Generated by Django 3.0.3 on 2020-03-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20200302_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='server',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='server',
            name='mem',
        ),
        migrations.RemoveField(
            model_name='server',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='server',
            name='status',
        ),
        migrations.RemoveField(
            model_name='server',
            name='use',
        ),
        migrations.RemoveField(
            model_name='server',
            name='uuid',
        ),
    ]
