# Generated by Django 3.0.3 on 2020-03-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_server_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='sn',
            field=models.CharField(blank=True, db_index=True, help_text='SN', max_length=40, null=True, verbose_name='SN'),
        ),
    ]
