# Generated by Django 3.0.3 on 2020-03-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_server_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='mem',
            field=models.CharField(blank=True, default=None, help_text='内存信息', max_length=100, verbose_name='内存信息'),
        ),
    ]
