# Generated by Django 3.0.3 on 2020-03-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_server_mem'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='use',
            field=models.CharField(default=None, help_text='用途', max_length=35, verbose_name='用途'),
        ),
        migrations.AddField(
            model_name='server',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, help_text='UUID', max_length=100, null=True, unique=True, verbose_name='UUID'),
        ),
    ]
