# Generated by Django 3.0.3 on 2020-03-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0011_auto_20200303_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='use',
        ),
    ]
