# Generated by Django 3.0.3 on 2020-03-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_remove_server_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='model_name',
            field=models.CharField(blank=True, default=None, help_text='型号', max_length=255, verbose_name='型号'),
        ),
    ]
