# Generated by Django 3.0.3 on 2020-03-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0013_server_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='use',
            field=models.CharField(default=None, help_text='用途', max_length=35, verbose_name='用途'),
        ),
    ]
