# Generated by Django 3.0.3 on 2020-03-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0014_server_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.CharField(db_index=True, help_text='状态', max_length=32, null=True, verbose_name='状态'),
        ),
    ]
