# Generated by Django 3.0.3 on 2020-03-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0015_server_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='os_type',
            field=models.CharField(help_text='操作系统类型', max_length=32, null=True, verbose_name='操作系统类型'),
        ),
    ]
