# Generated by Django 3.0.3 on 2020-03-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0016_server_os_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='network_name',
            field=models.CharField(help_text='网卡设备名', max_length=255, null=True, verbose_name='网卡设备名'),
        ),
    ]
