# Generated by Django 3.0.3 on 2020-03-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0017_server_network_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='network_mac',
            field=models.CharField(help_text='网卡mac地址', max_length=32, null=True, verbose_name='网卡mac地址'),
        ),
    ]
