# Generated by Django 3.0.3 on 2020-03-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0018_server_network_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='dict_size',
            field=models.CharField(help_text='硬盘大小', max_length=32, null=True, verbose_name='硬盘大小'),
        ),
        migrations.AddField(
            model_name='server',
            name='disk_name',
            field=models.CharField(help_text='硬盘名', max_length=32, null=True, verbose_name='硬盘名'),
        ),
    ]
