# Generated by Django 3.0.3 on 2020-03-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0019_auto_20200305_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='dict_size',
            new_name='disk_size',
        ),
    ]
