# Generated by Django 3.0.3 on 2020-03-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0020_auto_20200305_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cpu',
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU型号')),
                ('cpu_count', models.PositiveSmallIntegerField(default=1, verbose_name='物理CPU个数')),
                ('cpu_core_count', models.PositiveSmallIntegerField(default=1, verbose_name='CPU核数')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server', verbose_name='所在服务器')),
            ],
            options={
                'db_table': 'resources_cpu',
            },
        ),
    ]
