# Generated by Django 3.0.3 on 2020-03-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0021_auto_20200308_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu',
            field=models.CharField(blank=True, default=None, help_text='CPU信息', max_length=250, verbose_name='CPU信息'),
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
    ]
