# Generated by Django 3.0.3 on 2020-03-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0022_auto_20200308_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cpu',
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_core_count',
            field=models.CharField(blank=True, default=None, help_text='CPU核数', max_length=3, verbose_name='CPU核数'),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_count',
            field=models.CharField(blank=True, default=None, help_text='物理CPU个数', max_length=3, verbose_name='物理CPU个数'),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_model',
            field=models.CharField(blank=True, default=None, help_text='CPU信息', max_length=250, verbose_name='CPU型号'),
        ),
    ]
