# Generated by Django 3.0.3 on 2020-03-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0023_auto_20200308_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='cpu_model',
            new_name='cpu',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cpu_core_count',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cpu_count',
        ),
    ]
