# Generated by Django 3.0.3 on 2020-03-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0024_auto_20200308_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_core_count',
            field=models.CharField(blank=True, default=None, help_text='CPU核数', max_length=3, verbose_name='CPU核数'),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_count',
            field=models.CharField(blank=True, default=None, help_text='物理CPU个数', max_length=3, verbose_name='物理CPU个数'),
        ),
    ]
