# Generated by Django 3.0.3 on 2020-03-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0025_auto_20200308_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cpu_core_count',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cpu_count',
        ),
    ]
