# Generated by Django 3.0.3 on 2020-03-16 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0027_auto_20200316_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cpu_core_count',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cpu_count',
        ),
    ]
