# Generated by Django 3.0.3 on 2020-03-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0028_auto_20200316_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='os_type',
        ),
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.IntegerField(db_index=True, default=0, help_text='机器类型', verbose_name='机器类型'),
        ),
    ]
