# Generated by Django 3.0.3 on 2020-03-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0029_auto_20200327_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(help_text='机器类型', max_length=16, verbose_name='机器类型'),
        ),
    ]
