# Generated by Django 3.0.3 on 2020-03-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0030_auto_20200327_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(help_text='主机类型', max_length=32, null=True, verbose_name='主机类型'),
        ),
    ]
