# Generated by Django 3.0.3 on 2020-04-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0033_auto_20200327_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_use',
            field=models.CharField(help_text='CPU使用率', max_length=12, null=True, verbose_name='CPU使用率'),
        ),
        migrations.AddField(
            model_name='server',
            name='mem_use',
            field=models.CharField(help_text='内存使用率', max_length=12, null=True, verbose_name='内存使用率'),
        ),
    ]
