# Generated by Django 3.0.3 on 2020-03-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hadware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=36, null=True, verbose_name='名称')),
                ('manufacturer', models.CharField(help_text='厂商', max_length=255, verbose_name='厂商')),
                ('model_name', models.CharField(help_text='名称', max_length=36, null=True, verbose_name='型号')),
                ('work_voltage', models.CharField(help_text='工作电压', max_length=12, null=True, verbose_name='工作电压')),
                ('re_inputvoltage', models.CharField(help_text='推荐输入电压', max_length=12, null=True, verbose_name='推荐输入电压')),
                ('max_inputvoltage', models.CharField(help_text='极限输入电压', max_length=12, null=True, verbose_name='极限输入电压')),
                ('flash', models.CharField(help_text='闪存', max_length=64, null=True, verbose_name='闪存')),
                ('sram', models.CharField(help_text='SRAM', max_length=64, null=True, verbose_name='SRAM')),
            ],
            options={
                'db_table': 'resources_hadware',
            },
        ),
    ]
