# Generated by Django 3.0.3 on 2020-03-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hadware',
            new_name='Hardware',
        ),
        migrations.AlterModelTable(
            name='hardware',
            table='resources_hardware',
        ),
    ]
