# Generated by Django 3.0.3 on 2020-03-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20200313_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='nums',
            field=models.IntegerField(help_text='数量', max_length=32, null=True, verbose_name='数量'),
        ),
    ]
