# Generated by Django 3.0.3 on 2020-03-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_hardware_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='nums',
            field=models.IntegerField(help_text='数量', null=True, verbose_name='数量'),
        ),
    ]
